services:

  app:
    container_name: App
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Demo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=cache
    depends_on:
      - db
      - cache
    networks:
      - app-network

  db:
    image: postgres
    container_name: Postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=Demo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  cache:
    image: redis
    container_name: Redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data
    networks:
      - app-network

volumes:
  db-data:
  cache-data:

networks:
  app-network:
    driver: bridge