services:

  # Uygulamayı docker üzerinde kaldırmak için commenti kaldır
  #  app:
  #    container_name: SpringApp
  #    build: .
  #    image: demo-app:1.0 # build ile oluşan image'i 1.0 olarak tagler
  #    pull_policy: never # docker hub üzerinde bu tag var mı diye kontrol etmemesi için komut
  #    ports:
  #      - "8080:8080"
  #      - "5005:5005" # Debug portu *ekstra
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Demo
  #      - SPRING_DATASOURCE_USERNAME=postgres
  #      - SPRING_DATASOURCE_PASSWORD=test
  #      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #      - SPRING_DATA_REDIS_HOST=cache
  #      - TZ=Europe/Istanbul
  #    depends_on:
  #      - db
  #      - cache
  #      - kafka
  #    networks:
  #      - app-network

  db:
    image: postgres:18.0
    container_name: Postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=Demo
    ports:
      - "5432:5432"
    command: > # insert-update-delete loglarını basmak için db komutu
      postgres
      -c log_statement=mod
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - app-network

  cache:
    image: redis:8.2.3
    container_name: Redis
    restart: always
    command: redis-server --requirepass redis-password
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data
    networks:
      - app-network

  kafka:
    image: apache/kafka:4.1.0
    container_name: Kafka
    restart: always
    ports:
      - '9092:9092'
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-config:/mnt/shared/config
      - kafka-secrets:/etc/kafka/secrets
    networks:
      - app-network

volumes:
  db-data:
  cache-data:
  kafka-data:
  kafka-config:
  kafka-secrets:

networks:
  app-network:
    driver: bridge