#Spring
spring:
  application:
    name: demo
  jackson:
    time-zone: Europe/Istanbul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/Demo'
    username: postgres
    password: test
  data:
    redis:
      host: localhost
      password: redis-password
      port: 6379
      database: 0
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

#JWT
jwt:
  secret: KWp1IEiwQNyQSnrZnjTmQMRtcrMtiEJT2HqFIBT0+9/Zn+bEfICHjwb8pvIqnCfloLKtJ5R5+0v7KPhGxnf9UQ==
  expiration-ms: 3600000  # 1H

#Logging
logging:
  level:
    org.apache.kafka: warn
    root: info
#  file:
#    name: logs/app.log
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

#Swagger
springdoc:
  swagger-ui:
    path: /swagger
    enabled: true
    display-request-duration: true
    filter: true
    operations-sorter: alpha
    tags-sorter: alpha
    # use-root-path: true       #localhost:8080 üzerinden swagger açar